config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "chatroom#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post "message", to: "messages#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username,
            uniqueness: true,
            presence: true,
            length: { minimum: 3, maximum: 15 }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action!"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    if message.save
      redirect_to root_path
    end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [ :new, :create ]

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    puts "Session is #{session[:user_id]}"
    flash[:success] = "You have successfully logged in!"
    redirect_to root_path
    else
      flash.now[:error] = "Invalid login credentials!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out successfully!"
    redirect_to login_path
  end

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in!"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h1 class="d-flex flex-column-reverse align-items-center justify-content-center fw-semibold fs-4 font-serif text-center">
  Say Something...!
  <img src="/fav.png", alt="icon", width: 32, height: 32, class="rounded-circle p-1 my-1 border border-light shadow-sm">
</h1>
<div class="d-flex gap-4 my-5">
  <!-- Chat Area -->
  <div class="w-100 me-3 border border-secondary p-4 shadow rounded" style="flex: 1;">
    <div id="message-container" class="d-flex flex-column gap-3 py-4 overflow-auto" style="max-height: 24rem;">
      <%= render @messages %>
    </div>
    
  <div>
    <%= form_with model: @message, url: message_path, method: :post, html: { role: "form" }, remote: true do |f| %>
      <div class="d-flex gap-3 align-items-center mt-3">
        <div class="flex-fill">
          <%= f.text_field :body, placeholder: "Enter a message...", class: "form-control" %>
        </div>
        <div class="text-warning">
          <%= f.button class: "btn btn-link p-0" do %>
          <i class="fas fa-edit fs-3 cursor-pointer"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  </div>

  <!-- Sidebar -->
  <div class="d-flex flex-column gap-2 border border-secondary shadow p-4 bg-dark text-white rounded" style="width: 20%;">
    <%= link_to "Home", root_path, class: "btn btn-dark text-start #{'bg-secondary' if current_page?(root_path)}" %>
    <%= link_to "Messages", root_path, class: "btn btn-dark text-start" %>
    <%= link_to "Friends", root_path, class: "btn btn-dark text-start" %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div>
    <h5>
      <%= message_content %>
    </h5>
  </div>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom border-body mt-2 rounded-4">
  <div class="container-fluid">
    <%= link_to 'Chatroom', root_path, class:"navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Messages</a>
        </li>
      </ul>
      <div class="d-flex justify-content-between align-items-center gap-3">
        <div class="nav-item dropdown">
          <a class="nav-link text-white dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person"></i> Account
          </a>
          <ul class="dropdown-menu">
            <%if logged_in? %>
              <li>
                <%= link_to "Log out", logout_path, class:"dropdown-item", data: {turbo_method: :delete} %>
              </li>
            <%else%>
              <li>
                <%= link_to "Login", login_path, class:"dropdown-item" %>
              </li>
              <hr>
              <li>
                <%= link_to "Signup", login_path, class:"dropdown-item" %>
              </li>
            <%end%>
          </ul>
        </div>
        <% if logged_in? %>
          <%= button_to "Logout", logout_path, class:"btn btn-primary text-white", method: :delete %>
        <%else%>
          <%= button_to "Login", login_path, class:"btn btn-primary text-white", method: :get %>
        <%end%>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Message App" %></title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"/>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= render 'layouts/messages'%>
    <%= render 'layouts/navigation'%>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div>
  <em><%= message.user.username %></em>: <%=message.body%>
</div>